model: "deeper"
data_dir: "../chest_xray/chest_xray"
batch_size: 32
lr: 0.001
num_epochs: 8
seed: 42

augmentation: true
weighted_sampling: true
num_channels: 1
normalize: false

checkpoint_path: "checkpoints/pneumonia_deeper_cnn.pth"

thresholds: [0.5, 0.6, 0.7, 0.8, 0.85, 0.9]
